### ISSUE TITLE
What is the composition of the imagenet-100 dataset?

### ISSUE THREAD

**Issue by song-leap** [yebo0216best/LPS-main#1]
Hello!
Thank you for sharing your work.
Could you please tell me how many images are in each class in the imagenet100 dataset you used? I did a lot of searching, and everyone seems to be using different amounts of data.

**Comment by yebo0216best** [comment]
Thank you for your interest in our latest work LPS! Considering that ORCA only provides the classes and sequence for Imagenet100 in the source code, we directly used the official publicly available dataset 'ilsvrc/2012/train_t12' for splitting, to facilitate further comparison.
